[package]
name = "bot-randomizer-panel"
version = "1.0.0"
description = "Local configuration panel for CS2 Bot Randomizer"
authors = ["unicbm"]
edition = "2021"

[lib]
name = "bot_randomizer_panel_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
